apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-address-admin-grpc-gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-address-admin-grpc-gateway
        project: service-address-admin
    spec:
      imagePullSecrets:
      - name: pi-devops-docker-registry
      containers:
      - name: service-address-admin-grpc-gateway
        image: asia.gcr.io/pi-devops/service-address-grpc-gateway:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: GATEWAY_PORT
          value: "8080"
        - name: CORS_ALLOWED_ORIGINS
          value: "*"
        # service-address-admin-backend
        - name: SERVICE_ADDRESS_SORTING_SERVICE_HOST
          value: service-address-admin-backend
        - name: SERVICE_ADDRESS_SORTING_SERVICE_PORT
          value: $(SERVICE_ADDRESS_ADMIN_BACKEND_SERVICE_PORT_GRPC)
