apiVersion: v1
kind: Service
metadata:
  name: service-address-admin-backend
  labels:
    app: service-address-admin-backend
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: grpc
  selector:
    app: service-address-admin-backend

