// Copyright (c) 2017 Practice Insight Pty Ltd. All rights reserved.
//jshint esversion:6
//@flow
export const FETCH_NEXT_UNSORTED_SERVICE_ADDRESS = "FETCH_NEXT_UNSORTED_SERVICE_ADDRESS";
export const SEARCH_LAW_FIRMS = "SEARCH_LAW_FIRMS";
export const ASSIGN_SERVICE_ADDRESS = "ASSIGN_SERVICE_ADDRESS";
export const UNSORT_SERVICE_ADDRESS = "UNSORT_SERVICE_ADDRESS"
export const CREATE_LAW_FIRM = "CREATE_LAW_FIRM";
export const SET_SERVICE_ADDRESS_AS_NON_LAW_FIRM = "SET_SERVICE_ADDRESS_AS_NON_LAW_FIRM";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const UNDO_SERVICE_ADDRESS = "UNDO_SERVICE_ADDRESS";
export const PRE_FETCH_NEXT_UNSORTED_SERVICE_ADDRESS = "PRE_FETCH_NEXT_UNSORTED_SERVICE_ADDRESS";
export const SKIP_SERVICE_ADDRESS = "SKIP_SERVICE_ADDRESS";
export const SET_INSUFFICIENT_INFO_STATUS = "SET_INSUFFICIENT_INFO_STATUS";