// Copyright (c) 2017 Practice Insight Pty Ltd. All rights reserved.
//jshint esversion:6
//@flow
export const NAMESPACE = "ROOT";
export const CREATE_FIRM = NAMESPACE + "/CREATE_FIRM";
export const CLOSE_FIRM_DIALOG = NAMESPACE + "/CLOSE_FIRM_DIALOG";
export const SORT_SERVICE_ADDRESS = NAMESPACE + "/SORT_SERVICE_ADDRESS";
export const UNSORTED_SERVICE_ADDRESS_FULFILLED = NAMESPACE + "/UNSORTED_SERVICE_ADDRESS_FULFILLED";
export const UNSORTED_SERVICE_ADDRESS_FETCH_ERROR = NAMESPACE + "/UNSORTED_SERVICE_ADDRESS_FETCH_ERROR";
export const SERVICE_ADDRESS_UNSORTED = NAMESPACE + "/SERVICE_ADDRESS_UNSORTED"
export const START_FETCH = NAMESPACE + "/START_FETCH";
export const UNSORT_SERVICE_ADDRESS = NAMESPACE + "/UNSORT_SERVICE_ADDRESS";
export const UNDO_COMPLETED = NAMESPACE + "/UNDO_COMPLETED";
export const ERROR = NAMESPACE + "/ERROR";
